# Generated by Django 2.2.4 on 2019-08-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Http_connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yname', models.CharField(default='', max_length=100, verbose_name='用例名称')),
                ('state', models.CharField(choices=[('J', '禁用'), ('Q', '启用')], default='J', max_length=10, verbose_name='状态')),
                ('hosts', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='all服务器')),
                ('host', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='单个服务器')),
                ('path', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='异常接口')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '异常返回',
                'verbose_name_plural': '异常返回',
                'db_table': 'box_http_connect',
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='参数')),
                ('value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='参数值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '参数异常',
                'verbose_name_plural': '参数异常',
                'db_table': 'box_param',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=100, verbose_name='用例名称')),
                ('state', models.CharField(choices=[('J', '禁用'), ('Q', '启用')], default='J', max_length=10, verbose_name='状态')),
                ('old', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='正常返回数据')),
                ('new', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='模拟异常数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '异常返回',
                'verbose_name_plural': '异常返回',
                'db_table': 'box_response',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='用例名称')),
                ('state', models.CharField(choices=[('J', '禁用'), ('Q', '启用')], default='J', max_length=10, verbose_name='状态')),
                ('host', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='过滤服务器')),
                ('path', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='过滤接口')),
                ('hosta', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='all服务器')),
                ('hostd', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='单个服务器')),
                ('paths', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='异常接口路径')),
                ('hosty', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='异常服务器')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('query', models.ManyToManyField(blank=True, default='', null=True, to='box_request.Param', verbose_name='参数')),
            ],
            options={
                'verbose_name': '异常请求',
                'verbose_name_plural': '异常请求',
                'db_table': 'box_request',
            },
        ),
    ]
